namespace Gley.Localization
{
	public enum WordIDs
	{
		bundles_title = 12,
		Dailyreward_des1 = 24,
		Dailyreward_des2 = 25,
		Dailyreward_remainingTime = 26,
		Dailyreward_title = 23,
		gameui_hints = 22,
		gameui_level = 16,
		gameui_move = 17,
		gameui_reset = 21,
		gameui_size = 18,
		gameui_target = 19,
		gameui_undo = 20,
		OutofhintPop_ad = 6,
		OutofhintPop_des = 5,
		OutofhintPop_store = 7,
		OutofhintPop_title = 4,
		PacklockPop_cont = 15,
		PacklockPop_des = 14,
		PacklockPop_title = 13,
		RewardAdPop_continue = 10,
		RewardAdPop_des = 9,
		RewardAdPop_title = 8,
		SettingPop_lang = 30,
		SettingsPop_music = 1,
		SettingsPop_sound = 2,
		SettingsPop_title = 0,
		SettingsPop_version = 3,
		StorePop_title = 11,
		Timeout_continue = 28,
		Timeout_des = 29,
		Timeout_title = 27,
		winpop_des = 32,
		winpop_next = 31,
	}
}